# Generated by Django 4.1.3 on 2024-09-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_user_role_user_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_id',
        ),
    ]
