# Generated by Django 4.1.3 on 2024-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
